# Site settings
title: GitBucket News
#email: your-email@domain.com
description: "GitBucket is a GitHub clone powered by Scala."
baseurl: "http://takezoe.github.io/gitbucket"
url: "http://takezoe.github.io/gitbucket"

# Build settings
#markdown: kramdown
#permalink: prettay

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink",
                 "tables", "with_toc_data"]
